csvqb/csvqb/models/cube/cube.py, csvqb/csvqb/tests/test-cases/configloaders/bottles-test-files/bottles-data.csv, csvqb/csvqb/tests/test-cases/configloaders/bottles-test-files/bottles-info.json, csvqb/csvqb/tests/unit/configloaders/infojsontests.py
1.QbMultiMeasureDimension column is defined with the names of the existing measures which are defined in csvwlib/csvqb/csvqb/tests/test-cases/configloaders/bottles-test-files/bottles-info.json correctly loaded.
2.QbMultiUnits column is defined with the names of the existing units which are defined in /Users/santhoshthangavel/projects/csvwlib/csvqb/csvqb/tests/test-cases/configloaders/bottles-test-files/bottles-data.csv correctly loaded.
3.URIs for the measures and units are the full URIs, not just their short identifiers.
4.CubeMetadata model has following properties.'base_uri', 'creator', 'description', 'issued', 'keywords', 'landing_page', 'license', 'public_contact_point', 'publisher', 'summary', 'themes', 'title' and 'Uri_safe_identifier'
5.Class CubeMetadata and JSON schema is …
=> Unit test info.json population of multiple-measure-dimension classes (and units) from info.json#67

csvqb/csvqb/tests/unit/writers/qbwritertests.py, csvqb/csvqb/writers/qbwriter.py
The PR adds tests ensuring the following:
- URIs are correctly inferred for dimensions/attributes/measures/units when outputting CSV-W.
- URIs for Concepts are correctly inferred from conventionaly defined ConceptScheme URIs allowing us to infer the `propertyUrl` for a dimension's column.
- `QbColumn.output_uri_template` correctly overrides the default value we infer for the CSV-W column's `propertyUrl`.
- Defining a `SuppressedCsvColumn` sets `"suppressOutput": true` on the corresponding CSV-W column.
- Virtual columns for unit and measure are correctly generated where the dataset has a single measure and/or unit.
https://github.com/GSS-Cogs/csvwlib/issues/64
=> Issue #64 - Implementing tests for the QbWriter class.

csvqb/csvqb/tests/unit/cube/qb/errorvalidation.py, csvqb/csvqb/utils/qb/cube.py
1.QB with an existing dimension and without an output_uri_template is defined.
2.A Validation error is generated when user provides an existing dimension but not a column.output_uri_template.
3.Test case written to capture the number of errors.
#83
=> Issue#83 - Add a validation error when user uses an ExistingDimension without providing a column.output_uri_template.

csvqb/csvqb/models/cube/csvqb/catalog.py, csvqb/csvqb/models/cube/csvqb/components/observedvalue.py, csvqb/csvqb/models/rdf/qbdatasetincatalog.py, csvqb/csvqb/tests/behaviour/qbwriter.feature, csvqb/csvqb/tests/behaviour/skoscodelists.feature, csvqb/csvqb/tests/behaviour/steps/qbwriter.py, csvqb/csvqb/tests/behaviour/steps/skoscodelists.py, csvqb/csvqb/tests/unit/utils/uritests.py, csvqb/csvqb/utils/dict.py, csvqb/csvqb/utils/uri.py, csvqb/csvqb/writers/qbwriter.py, csvqb/csvqb/writers/skoscodelistwriter.py, devtools/devtools/behave/csv2rdf.py, devtools/devtools/behave/csvlint.py, devtools/devtools/behave/rdf.py, sharedmodels/sharedmodels/rdf/qb.py
Adds `dcat:Dataset` class to the `qb:DataSet` with the appropriate metadata which should be enough for PMD's needs.
Closes issue #23.
=> Issue #23 - Adding DCAT metadata to the qb:DataSet output

csvqb/csvqb/models/cube/cube.py, csvqb/csvqb/tests/unit/cube/test_cube_errorvalidation.py
Suitable error message is generated when
1.  A cube with two columns with the same title is defined.
2. Defining a column with a title that doesn't exist in the DataFrame.
3.  A column in input DataFrame doesn't have a column mapping.
#62
=> Issue#62 Test cube validation 

csvqb/Pipfile, csvqb/Pipfile.lock, csvqb/csvqb/configloaders/infojson.py, csvqb/csvqb/models/cube/catalog.py, csvqb/csvqb/models/cube/columns.py, csvqb/csvqb/models/cube/csvqb/catalog.py, csvqb/csvqb/models/cube/csvqb/columns.py, csvqb/csvqb/models/cube/csvqb/components/attribute.py, csvqb/csvqb/models/cube/csvqb/components/codelist.py, csvqb/csvqb/models/cube/csvqb/components/datastructuredefinition.py, csvqb/csvqb/models/cube/csvqb/components/dimension.py, csvqb/csvqb/models/cube/csvqb/components/measure.py, csvqb/csvqb/models/cube/csvqb/components/observedvalue.py, csvqb/csvqb/models/cube/csvqb/components/unit.py, csvqb/csvqb/models/cube/cube.py, csvqb/csvqb/models/pydanticmodel.py, csvqb/csvqb/models/uriidentifiable.py, csvqb/csvqb/models/validationerror.py, csvqb/csvqb/tests/unit/configloaders/test_infojsontests.py, csvqb/csvqb/tests/unit/cube/qb/test_cubeqb_errorvalidation.py, csvqb/csvqb/tests/unit/pydantic/test_cube.py, csvqb/csvqb/tests/unit/pydantic/test_cubemetadata.py, csvqb/csvqb/tests/unit/test_baseunit.py, csvqb/csvqb/writers/qbwriter.py
**N.B. This PR relies on 3 separate bug fixes to the pydantic library which are currently stored in the forked repo at https://github.com/robons/pydantic/**
**N.B. - This does not allow us to start using specific [validators](https://pydantic-docs.helpmanual.io/usage/validators/#dataclass-validators) on a per-attribute basis. This is something we might want to look into in future.**
This PR makes quite a change to our code-base. It enables us to easily validate that all of a class' attributes match the associated static type annotations. To support this, and to make a bit easier, it switches the majority of csvqb's models over to being [dataclasses](https://docs.python.org/3/library/dataclasses.html).
[Dataclasses](https://docs.python.org/3/library/dataclasses.html) give us a simpler way …
=> Issue #57 - Introducing DataClasses and Pydantic (Static Type) Validation

csvqb/Pipfile, csvqb/Pipfile.lock, csvqb/csvqb/README.md, csvqb/csvqb/cli/build.py, csvqb/csvqb/cli/entrypoint.py, csvqb/csvqb/configloaders/infojson.py, csvqb/csvqb/models/cube/cube.py, csvqb/csvqb/models/cube/qb/components/unit.py, csvqb/csvqb/tests/behaviour/cli.feature, csvqb/csvqb/tests/behaviour/steps/cli.py, csvqb/csvqb/tests/test-cases/configloaders/validation-error/data.csv, csvqb/csvqb/tests/test-cases/configloaders/validation-error/info.json, csvqb/csvqb/tests/unit/configloaders/test_infojsontests.py, csvqb/setup.py, devtools/devtools/behave/file.py
Satisfies issue #108.
```bash
Usage: csvqb [OPTIONS] COMMAND [ARGS]...
CSVqb - a tool to generate qb-flavoured CSV-W cubes.
Options:
-h, --help  Show this message and exit.
Commands:
build  Build a qb-flavoured CSV-W from a tidy CSV.
```
Build the qb-flavoured CSV-Ws from an *info.json V1* file.
```bash
Usage: csvqb build [OPTIONS] TIDY_CSV_PATH
Build a qb-flavoured CSV-W from a tidy CSV.
Options:
-c, --config CONFIG_PATH        Location of the info.json file containing
the QB column mapping definitions.
[required]
-o, --out OUT_DIR               Location of the CSV-W outputs.  [default:
out]
--fail-when-validation-error / --ignore-validation-errors
Fail when validation errors occur or ignore
validation errors and continue generating a
CSV-W.  [default: fail-when-validation-
error] …
```
=> Issue #108 - Create CLI for csvqb

csvqb/csvqb/tests/behaviour/qbwriter.feature, csvqb/csvqb/tests/behaviour/steps/qbwriter.py, csvqb/csvqb/tests/test-cases/configloaders/multi-measure-info-json-test-files/multi-measure-data.csv, csvqb/csvqb/tests/test-cases/configloaders/multi-measure-info-json-test-files/multi-measure-info.json, csvqb/csvqb/tests/test-cases/configloaders/single-measure-info-json-test-files/single-measure-data.csv, csvqb/csvqb/tests/test-cases/configloaders/single-measure-info-json-test-files/single-measure-info.json, csvqb/csvqb/tests/unit/writers/test_qbwriter.py, csvqb/csvqb/writers/qbwriter.py
1.A cube is loaded using the info.json with a CSV.
2.Cube&qb validation succeeds.
3.Cube is serialised to CSV-W
4.csvlint validation succeeds
5.csv2rdf succeeds
6.RDF passes "SKOS, qb" SPARQL tests
7.Ouput ttl is compared with ttl as we do in gss-utils
8.Additional ttl is appended to the resulting RDF for multi-measure-data.csv as the Measure dimension and unit attribute defined in info.json is an existing dimension and attribute.
#68
=> Issue-68 Behaviour test info.json config.loader

Jenkinsfile, csvqb/csvqb/cli/build.py, csvqb/csvqb/cli/entrypoint.py, csvqb/csvqb/configloaders/infojson.py, csvqb/csvqb/configloaders/infojson1point1/columnschema.py, csvqb/csvqb/configloaders/infojson1point1/mapcolumntocomponent.py, csvqb/csvqb/models/cube/catalog.py, csvqb/csvqb/models/cube/qb/catalog.py, csvqb/csvqb/models/pydanticmodel.py, csvqb/csvqb/tests/behaviour/cli.feature, csvqb/csvqb/tests/behaviour/steps/cli.py, csvqb/csvqb/tests/test-cases/configloaders/catalog-metadata.json, csvqb/csvqb/tests/unit/configloaders/test_infojsontests.py, csvqb/csvqb/tests/unit/cube/qb/test_catalog_metadata.py, sharedmodels/sharedmodels/dataclassbase.py, sharedmodels/sharedmodels/tests/unit/test_dataclassbase.py
- Added functionality to read/write dataclasses to/from JSON.
- Added functinoality to override specific properties on said dataclasses (useful for overriding CatalogMetadata with the scraper's metadata).
- Added param to csvqb CLI to accept additonal catalog metadata JSON to override defaults from info.json file.
Part of Issue #28.
=> Issue #28 - Allowing CatalogMetadata Serialisation/Deserialisation to/from JSON

sharedmodels/sharedmodels/dataclassbase.py, sharedmodels/sharedmodels/tests/unit/test_dataclassbase.py
Oh the pain of developing coupled projects across different repositories.
Found this problem when integrating the sharedmodels functionality into gss-utils.
=> Issue #28 - Fixing serialisation/deserialisation of date types as well as datetime types

csvcubed-devtools/csvcubeddevtools/behaviour/rdf.py, csvcubed-pmd/csvcubedpmd/csvwcli/__init__.py, csvcubed-pmd/csvcubedpmd/dcatcli/__init__.py, csvcubed-pmd/csvcubedpmd/dcatcli/pmdify.py, csvcubed-pmd/csvcubedpmd/main.py, csvcubed-pmd/csvcubedpmd/models/CsvCubedOutputType.py, csvcubed-pmd/poetry.lock, csvcubed-pmd/tests/behaviour/csvwcommandline.feature, csvcubed-pmd/tests/behaviour/dcatcommandline.feature, csvcubed-pmd/tests/test-cases/dcatcli/period.csv, csvcubed-pmd/tests/test-cases/dcatcli/period.csv-metadata.json, csvcubed-pmd/tests/test-cases/dcatcli/period.table.json, csvcubed-pmd/tests/test-cases/dcatcli/single-measure-bulletin.csv, csvcubed-pmd/tests/test-cases/dcatcli/single-measure-bulletin.csv-metadata.json, csvcubed-pmd/tests/unit/dcatcli/test_pmdify.py
Added a new CLI command which strips out the DCAT catalog metadata out of the `file.csv-metadata.json` file and drops it into a `file.csv-metadata.json.nq` N-Quads file.
```
$ pmdutils dcat pmdify --help
Usage: pmdutils dcat pmdify [OPTIONS] CSVW_METADATA_FILE BASE_URI
DATA_GRAPH_URI CATALOG_METADATA_GRAPH_URI
Given a local CSV-W metadata.json file, re-work the DCATv2 metadata such
that it ends up in the format required for PMD.
Removes the expected DCAT metadata from the CSV-W metadata.json file and
outputs a new N-Quads file containing PMDCAT metadata at
<CSVW_METADATA_FILE>.nq
``` 
* `CSVW_METADATA_FILE` - the `.csv-metadata.json` CSV-W file.
* `BASE_URI` - the base URI which URIs inside the CSV-W are relative to (generally the URL of the directory holding the CSV-W).
* …
=> Issue #105 - PMDise Catalog Metadata

csvcubed-pmd/csvcubedpmd/csvwcli/__init__.py, csvcubed-pmd/csvcubedpmd/csvwcli/findwhere.py, csvcubed-pmd/csvcubedpmd/dcatcli/pmdify.py, csvcubed-pmd/csvcubedpmd/main.py, csvcubed-pmd/csvcubedpmd/utils/sparql.py, csvcubed-pmd/tests/behaviour/csvwcommandline.feature
```bash
$ pmdutils csvw find-where --help
Usage: pmdutils csvw find-where [OPTIONS] ASK_QUERY
Find all CSV-W metadata files within a given directory which match an ASK
query.
Options:
-i, --inside SEARCH_DIR  Directory in which to search for CSV-W Metadata
Files  [default: .]
-n, --negate             Negate the result of running the ASK query.
-h, --help               Show this message and exit.
```
example usage:
```bash
$ pmdutils csvw find-where "ASK WHERE { ?s a <http://www.w3.org/2004/02/skos/core#ConceptScheme>. }"
tests/test-cases/dcatcli/period.csv-metadata.json
```
=> Issue #105 - Adding CLI Command to find CSV-W files matching SPARQL ASK query

csvcubed-devtools/csvcubeddevtools/behaviour/rdf.py, csvcubed-pmd/csvcubedpmd/dcatcli/pmdify.py, csvcubed-pmd/tests/behaviour/dcatcommandline.feature
This is a requirement PMD imposes on the data we upload to it.
=> Fixing bug where `pmdcat` datatype wasn't added to the `qb:DataSet` or `skos:ConceptScheme` which had been added to a catalog.

csvcubed/csvcubed/utils/qb/standardise.py, csvcubed/csvcubed/writers/qbwriter.py, csvcubed/tests/unit/utils/qb/test_standardise.py, csvcubed/tests/unit/writers/test_qbwriter.py
When the observation values in a dataset are marked as integers, but a value is missing, pandas unhelpfully represents all of the interger values as decimals/floats/doubles. This means that the CSV-Ws we generate are invalid since they claim that the contents of the obs val column is an integer, but the values are actually decimals.
This PR addresses this bug and ensures that the datatype is correctly serialised to disk.  
Addressed Issue #360
=> Fixing bug in integer serialisation to CSV

csvcubed/csvcubed/cli/inspect/inspectsparqlmanager.py, csvcubed/definitions.py
The `_get_query_string_from_file` now finds the project root by using a variable defined at the `definitions.py` file. This file is at the project root.
=> Updates to project root path finding

external-docs/docs/guides/shape-data.md, external-docs/mkdocs.yml
Added documentation discussing the two shapes of data accepted by csvcubed and when you should use them.
Documentation can be seen in-action [here](https://ci.ukstats.dev/job/GSS_data/job/csvwlib/view/change-requests/job/PR-355/lastSuccessfulBuild/artifact/external-docs/site/guides/shape-data/index.html).
Satisfies Issue #17
=> Added documentation of Shaping your Data

csvcubed/csvcubed/readers/V1_0/templates/onsgeographies.json
"onsgeogrphy.json" was supposed to be named "onsgeographies.json"
=> renaming file to match that in preset_column_confg

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/request-further-guidance.md
Supplementary PR which adds normal markdown issue templates for bug reporting and requesting further guidance from the team. 
Related to Issue229 and [this PR](https://github.com/GSS-Cogs/csvcubed/pull/372)
Had to be added in a separate branch as the github interface for adding issue templates only gives the option to commit to main or open a PR in a new branch.
=> Update issue templates

Dockerfile
Since we have `apt-get update` and `apt-get install` in separate `RUN` statements inside the Dockerfile, the latter command was failing when building the container (without cache).
Docker best practices recommend combining the two commands into a single `RUN` statement since "Using apt-get update alone in a RUN statement causes caching issues and subsequent apt-get install instructions fail." This PR contains this update.
See https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run for reference.
=> Fixes added to the dockerfile

csvcubed-devtools/csvcubeddevtools/behaviour/csv2rdf.py
Switch to using a native/compiled version of csv2rdf for tests.
This makes use of: https://github.com/GSS-Cogs/csv2rdf-docker/tree/native which Alex put together a few weeks ago.
Have pushed as `gsscogs/csv2rdf:native` _for now_ .... you _could_ merge Alexs branch into master but I'm a little wary until we've run on it for a while (I'm imaging updating `csv2rdf:latest` before a release but not until then.... see if the wheels fall off in the meantime). Happy to take a steer on that though.
Runs as expected under both csvcubed and gss-utils.
While running `behave ./test/behaviours` against the `csvcubed` module (average across three runs):
`csv2rdf:native`: 3m
`csv2rdf:latest`: 8m
The tests on Jenkins give every appearence of speeding up but there's so many factors I don't even want to try …
=> Issue 459/native compiled csv2rdf

csvcubed/csvcubed/models/cube/qb/components/concept.py, csvcubed/csvcubed/readers/cubeconfig/v1_0/columnschema.py, csvcubed/csvcubed/readers/preconfiguredtemplates.py, csvcubed/tests/unit/readers/cubeconfig/v1_0/test_cube_from_config_json.py
The PR addresses a couple of bugs:
1. `<column_name>` substitution in column templates was generating invalid URI templates which didn't correctly reference the column.
2. The code which generated local date-time code lists was using the wrong property to make the decision. No testing existed to validate this.
Addresses issue #477
=> Correcting date time code list serialisation

external-docs/docs/guides/linked-data/licenses.md
supports PR: https://github.com/GSS-Cogs/GDP-vocabs/pull/13
I've only documented the V4 Creative Commons licenses, as there are strong recommendations not to use the earlier licences for data (as they don't cover data in databases). So while we support them I thought it was best to to advertise it.
=> update licence documentation

csvcubed/csvcubed/schema/codelist-config/v1_0/codelistconfig-example.jsonc, csvcubed/csvcubed/schema/codelist-config/v1_0/schema.json, csvcubed/csvcubed/schema/cube-config/v1_0/schema.json, csvcubed/csvcubed/schema/cube-config/v1_1/qbconfig-example.jsonc, csvcubed/csvcubed/schema/cube-config/v1_1/schema.json
This PR contains changes to the code list and cube config schemas so that the default is used instead of const.
=> Reverted const to default in schema

tests/behaviour/qbwriter.feature, tests/behaviour/skoscodelists.feature, tests/behaviour/steps/qbwriter.py
Adresses ticket #614
Previously, the two behaviour tests which verified that the csvcubed version specific metadata triples has been serialised correctly to the resultant RDF contained a hardcoded value for the version URI which caused the tests to fail when running under any other tag.
This PR has changed these two tests by adding an additional step to each of their respective scenarios which construct the correct triples using the version util function created in the [original ticket](https://github.com/GSS-Cogs/csvcubed/issues/541).
The assertion uses the same devtools function as the step `and the RDF should contain` but this couldn’t be wholly reused for this fix because we needed to add the version function call to the step definition instead of calling from `context.text`.
The new …
=> Issue 614 - prov-o csvcubed version number is harded coded in behaviour tests

pyproject.toml, tests/behaviour/qbwriter.feature, tests/behaviour/steps/qbwriter.py
rdflib raised a syntax error due to the "\r" char that was being picked up on the windows machine.
=> Fixing a bug in windows testing (regarding QbWriter)

src/csvcubed/utils/qb/standardise.py, tests/unit/cli/inspect/test_inspectdatasetmanager.py
Renaming categories on a pandas datacolumn in an in-place fashion yields a deprecation warning which isn't helpful for external users to see. 
This PR addresses #626 by avoiding in-place renaming of categories.
I also took the opportunity to remove some inplace replacements running in unrelated unit tests. Future versions of pandas will not support in-place replacement at all.
=> Rename pandas categories without inviting deprecation warning

.github/workflows/reusable-deploy.yaml
Added in the extra check for Pre-release tag(-rc before the last digit in the tag).
=> Ensuring we don't publish documentation for pre-release versions

src/csvcubed/writers/qbwriter.py, tests/behaviour/qbwriter.feature, tests/unit/writers/qbwriter/test_qbwriter.py
This was a quick fix to qbwriter.py where in a pivoted multi measure dataset, we were linking a slice to the corresponding observation values using the wrong predicate. This simply meant changing the predicate in this virtual column creation from qb:Observation to qb:observation, then adjusting the relevant tests so they expect the correct results when a CSV-W is generated.
Statisfied #697.
=> 697 Incorrect linking of slices to observations in pivoted shape

src/csvcubed/models/jsonvalidationerrors.py, src/csvcubed/readers/cubeconfig/v1/configdeserialiser.py, src/csvcubed/schema/cube-config/v1_4/schema.json, tests/test-cases/readers/cube-config/v1.0/schema_validation_errors/all_column_types_badly_defined.json, tests/unit/readers/cubeconfig/v1_0/test_json_schema_validation_errors.py
Does what it says on the tin. I've added a test case which demonstrates this functionality. The following is an example of how each column type behaves:
```
$ csvcubed build data.csv --config all_column_types_badly_defined.json
2023-02-20 12:15:58,034 - csvcubed.cli.build - WARNING - Schema Validation Error: $.columns.Amount - Unable to identify {'type': 'observations', "shouldn't": 'be here'}
If you meant to declare 'This column holds observed/recorded values', then:
- Additional properties are not allowed ("shouldn't" was unexpected)
(build.py:101)
2023-02-20 12:15:58,035 - csvcubed.cli.build - WARNING - Schema Validation Error: $.columns.Attr-1 - Unable to identify {'type': 'attribute', 'label': 'My best attribute', 'from_existing': 'http://example.com/attributes/some-attribute'}
If …
```
=> #715 - Filtering column JSON schema error messages displayed based on `type`.

src/csvcubed/models/cube/catalog.py, src/csvcubed/models/cube/columns.py, src/csvcubed/models/cube/qb/catalog.py, src/csvcubed/models/cube/qb/columns.py, src/csvcubed/models/cube/qb/components/arbitraryrdf.py, src/csvcubed/models/cube/qb/components/attribute.py, src/csvcubed/models/cube/qb/components/attributevalue.py, src/csvcubed/models/cube/qb/components/codelist.py, src/csvcubed/models/cube/qb/components/concept.py, src/csvcubed/models/cube/qb/components/dimension.py, src/csvcubed/models/cube/qb/components/measure.py, src/csvcubed/models/cube/qb/components/measuresdimension.py, src/csvcubed/models/cube/qb/components/observedvalue.py, src/csvcubed/models/cube/qb/components/unit.py, src/csvcubed/models/cube/qb/components/unitscolumn.py, src/csvcubed/models/uriidentifiable.py, src/csvcubed/models/validatedmodel.py, src/csvcubed/models/validationerror.py, src/csvcubed/utils/validations.py, tests/unit/utils/test_validations.py
PR to satisfy ticket #676
Changes the information shown to the user in the event of a validation error by adding `property_path` and `offending_value` properties to `ValidateModelPropertiesError`.
`property_path` replaces the existing `property_name` property and takes the form of a list which drills down from the highest validated object to the offending property. 
Combining this with the `offending_value` should make it clear to the user where the error lies and what needs to be changed to satisfy the validation.
All relevant unit tests have been altered to reflect this change and some new ones added to demonstrate scenarios where property paths are constructed as properties belonging to higher level objects or when they are nested in lists.
Other changes:
- Adding truncation (to 50 …
=> 676 validate model properties error

src/csvcubed/cli/inspectcsvw/metadataprinter.py, src/csvcubed/models/sparqlresults.py, src/csvcubed/utils/sparql_handler/data_cube_inspector.py, src/csvcubed/utils/sparql_handler/sparql_queries/select_is_pivoted_shape_data_set.sparql, src/csvcubed/utils/sparql_handler/sparqlquerymanager.py, tests/unit/cli/inspectcsvw/test_inspectdatasetmanager.py, tests/unit/cli/inspectcsvw/test_metadataprinter.py, tests/unit/utils/sparqlhandler/test_code_list_inspector.py, tests/unit/utils/sparqlhandler/test_csvw_inspector.py, tests/unit/utils/sparqlhandler/test_data_cube_inspector.py, tests/unit/utils/sparqlhandler/test_sparqlquerymanager.py
- Redundant tests removed from `test_sparqlquerymanager.py`
- Redundant SPARQL results classes removed from `sparqlresults.py`
- `output_str` property removed from `CatalogMetadata` class and moved to `MetadataPrinter`
- Cached inspector helpers replacing direct instantiation of `Inspector` classes in test files
- `IsPivotedShapeMeasureResult` renamed to `IsPivotedShapeResult` and associated functions updated
=> #740 remove unnecessary tests sparqlquerymanager

src/csvcubed/writers/skoscodelistwriter.py, tests/behaviour/skoscodelists.feature, tests/behaviour/steps/skoscodelists.py
Addresses bug ticket #822
csvw-check was finding an error in our cube outputs when they have a locally defined code list.
`tables.1.tableSchema: A @context node must be defined.`
To solve this issue, we have added an extra line when writing in `skoscodelistwriter.py` and specifically to the `table.json` files so that they begin with a @context node.
This change results in a `Valid CSV-W` message after running csvw-check. However, we wanted to include a test which would demonstrate this change but we are unable to use csvw-check in our behave tests until ticket #824 has been completed. Until then, we have added an extra step to one behave test which verifies that the `skoscodelistwriter` has included the node in the correct place. I have added a comment in the code to explain that this …
=> 822 context bug

external-docs/docs/dict_manual_definitions.txt, external-docs/docs/guides/example3.md, external-docs/docs/guides/inspect-api/example3.md, external-docs/docs/guides/inspect-api/index.md, external-docs/mkdocs.yml
This ticket was to create an external documentation page for a worked example of using the Inspect API to perform a statistical analysis. The examples allow an end user to understand how to generalise a statistical model so that it can be used to analyse different CSV-Ws without hardcoding column names.
Thoughts on improvements to the Inspect API that arose during the completion of this ticket have been added to ticket #796.
=> #777 worked example #3 for Inspect API docs

src/csvcubed/utils/csvdataset.py, tests/unit/inspect/test_inspectdatasetmanager.py
Addresses #856 in which when a column is titled `Value`and we need to use the pandas `melt()` function such as when calling `transform_dataset_to_canonical_shape()` which causes an error because pandas does not allow a melted dataframe to have a column named `Value`. 
This ticket adds a rather hacky workaround in which we catch any columns called `Value` and give the melt function a `value_name` of `Not-Value` (which is then used in the melted df). We then rename the `Not-Value` column from the melted df and pass this back.
Added a unit test to verify this functionality. Compares column names from the original dataframe are a subset of the ones in the melted df.
=> [BUG] Cannot use 'Value' as the column name for observation column

README.md
The link to the developer documentation was a relative URL (./docs/developer.md) in README.md which was being automatically expanded to https://pypi.org/project/csvcubed/docs/developer.md upon publishing to PyPI. This has been replaced with the absolute URL in README.md which should fix the issue.
All other links appear to be absolute so should be fine.
=> Updated link to developer documentation in README
