- csvqb/csvqb/configloaders/infojson.py
- csvqb/csvqb/models/cube/cube.py
> Moving `CubeMetadata.from_dict` to info.json loader. 

- .devcontainer/devcontainer.json
> devcontainer setup

- csvqb/csvqb/tests/behaviour/qbwriter.feature
- csvqb/csvqb/tests/behaviour/skoscodelists.feature
- csvqb/csvqb/tests/behaviour/steps/qbwriter.py
- csvqb/csvqb/tests/behaviour/steps/skoscodelists.py
- csvqb/csvqb/tests/unit/writers/test_qbwriter.py
- csvqb/csvqb/utils/qb/cube.py
- csvqb/csvqb/writers/qbwriter.py
- csvqb/csvqb/writers/skoscodelistwriter.py
- devtools/devtools/behave/rdf.py
I've added the foreign key constraints to the CSV-W we output. I had to re-work slightly how we output code-lists.
I also realised that I'd completely forgotten to add primary keys to the CSV-Ws so I added those to both the dataset and code-list CSV-Ws with some behaviour tests to boot.
This satisfies issue #69.
> Issue #69 - Adding local Foreign Key Constraints to CSV-W

- csvqb/csvqb/tests/unit/cube/qb/test_qb_dimension.py
1. Test case is added to check if NewQbDimension correctly extracts and creates a Valid NewQbCodeList & NewQbConcept
2.Unique concept labels are asserted
3.Asserted NewQbDimension concepts does not have a parent
4. Asserted to see if concept labels are converted into something that can be used in a URI path segment (pathify).
#86
> Issue#86 - Test `NewQbDimension.from_data

- Jenkinsfile
- sharedmodels/pyproject.toml
- sharedmodels/sharedmodels/rdf/resource.py
- sharedmodels/sharedmodels/tests/unit/rdf/test_resource_serialisation.py
Implemented tests as described in Issue #75.
> Issue #75 - Testing RDF Serialisation

- Jenkinsfile
- csvqb/Pipfile.lock
- csvqb/csvqb/cli/build.py
- csvqb/csvqb/configloaders/infojson.py
- csvqb/csvqb/configloaders/infojson1point1/columnschema.py
- csvqb/csvqb/inputs.py
- csvqb/csvqb/models/cube/cube.py
- csvqb/csvqb/models/cube/qb/components/attribute.py
- csvqb/csvqb/models/cube/qb/components/measure.py
- csvqb/csvqb/tests/behaviour/qbwriter.feature
- csvqb/csvqb/tests/behaviour/steps/qbwriter.py
- csvqb/csvqb/tests/test-cases/configloaders/validation-error/data.csv
- csvqb/csvqb/tests/test-cases/configloaders/validation-error/info.json
- csvqb/csvqb/tests/unit/writers/test_qbwriter.py
- csvqb/csvqb/writers/qbwriter.py
- csvqb/setup.py
- devtools/devtools/behave/csv2rdf.py
- devtools/devtools/behave/csvlint.py
- devtools/devtools/behave/sparqltests.py
- Ensures that you can create attribute values from a column containing missing values (attributes are not required by default).
- Ensure that the observation's columns in the CSV-W point to the correct propertyUrl for the measure dimension/constant measure
- Ensure that the csvqb .whl package actually contains some code.
> Robons bug fix

- csvqb/Pipfile.lock
- csvqb/csvqb/models/cube/qb/components/attribute.py
- csvqb/csvqb/models/cube/qb/components/measure.py
- csvqb/csvqb/models/cube/qb/components/unit.py
- csvqb/csvqb/utils/qb/standardise.py
> Issue #28 - Upgrading pandas in csvqb to be compatible with currently used gss-utils version.

- csvqb/csvqb/tests/unit/writers/test_qbwriter.py
- csvqb/csvqb/writers/qbwriter.py
* Testing in unit tests
* Forgot about procedural programming
> implement `qb:order`

- csvcubed-devtools/poetry.lock
- csvcubed-devtools/pyproject.toml
- csvcubed-models/poetry.lock
- csvcubed-models/pyproject.toml
- csvcubed-pmd/poetry.lock
- csvcubed-pmd/pyproject.toml
- csvcubed/poetry.lock
- csvcubed/pyproject.toml
Now using csvcubed-pydantic, same as v0.1.0-rc1.
> Release_pydantic_relocation

- csvcubed-devtools/csvcubeddevtools/behaviour/rdf.py
- csvcubed-models/csvcubedmodels/rdf/dcat.py
- csvcubed-pmd/csvcubedpmd/dcatcli/pmdify.py
- csvcubed-pmd/tests/unit/dcatcli/test_pmdify.py
- csvcubed/csvcubed/models/cube/qb/catalog.py
- csvcubed/csvcubed/utils/uri.py
- csvcubed/csvcubed/utils/validators/uri.py
- csvcubed/tests/behaviour/CatalogMetadata.feature
- csvcubed/tests/behaviour/steps/CatalogMetadata.py
- csvcubed/tests/test-cases/MultipleLandingPageError/CatalogMetadata.json
Fixes have been made to support multiple landing pages, along with bdd tests.
> Muazzam chaud/issue211

- csvcubed/csvcubed/writers/qbwriter.py
- csvcubed/tests/behaviour/qbwriter.feature
- csvcubed/tests/behaviour/steps/qbwriter.py
- csvcubed/tests/unit/writers/test_qbwriter.py
> Issue #264 - Adding the `qb:Observation` type and `qb:dataSet` types onto observations

- csvcubed/csvcubed/models/cube/cube.py
- csvcubed/csvcubed/models/cube/qb/components/attribute.py
- csvcubed/csvcubed/models/cube/validationerrors.py
- csvcubed/csvcubed/models/rdf/newattributevalueresource.py
- csvcubed/tests/behaviour/qbwriter.feature
- csvcubed/tests/unit/cube/qb/test_cubeqb_errorvalidation.py
Also improved the specificity of some of our exception handling to make it easier to debug where problems arise from.
> Fixing a bug where creating `NewQbAttributeValue`s from a data frame fails to validate when the values are not strings.

- csvcubed-devtools/csvcubeddevtools/behaviour/csvlint.py
- csvcubed-pmd/csvcubedpmd/dcatcli/pmdify.py
- csvcubed-pmd/tests/behaviour/dcatcommandline.feature
- csvcubed-pmd/tests/test-cases/dcatcli/itis-industry.csv
- csvcubed-pmd/tests/test-cases/dcatcli/itis-industry.csv-metadata.json
- csvcubed-pmd/tests/unit/dcatcli/test_pmdify.py
This should fix the problems detailed in #311 which cause the processing & upload of pipelines containing pre-defined local code-lists to fail.
> Issue #311 - Fixing processing of existing CSV-W code-lists

- csvcubed/csvcubed/schema/cube-config-schema.jsonc
Appears to be a lack of differentiation between New and Existing column types.
Column attributes could be extracted into lower level $defs.
> Draft Cube Config Schema json.

- csvcubed/csvcubed/models/cube/qb/components/dimension.py
- csvcubed/csvcubed/models/cube/qb/components/unit.py
- csvcubed/csvcubed/utils/csvw.py
- csvcubed/csvcubed/utils/dict.py
- csvcubed/csvcubed/utils/file.py
- csvcubed/csvcubed/utils/log.py
- csvcubed/csvcubed/utils/qb/cube.py
- csvcubed/csvcubed/utils/uri.py
- csvcubed/csvcubed/utils/validators/attributes.py
- csvcubed/csvcubed/utils/validators/file.py
- csvcubed/csvcubed/utils/validators/uri.py
- csvcubed/poetry.lock
- csvcubed/pyproject.toml
- csvcubed/tests/unit/conftest.py
- csvcubed/tests/unit/utils/test_uritests.py
Adding some bland colourless logging.
> Initial logging configuration functionality.

- csvcubed-devtools/csvcubeddevtools/behaviour/rdf.py
- csvcubed-pmd/csvcubedpmd/dcatcli/pmdify.py
- csvcubed-pmd/tests/behaviour/dcatcommandline.feature
- csvcubed-pmd/tests/unit/dcatcli/test_pmdify.py
Hoping to properly separate the catalogue metadata out into a separate graph.
Once this has successfully built and been merged in (and once the docker image has been published for pmdutils), this *should* fix the remaining problems with @RedWalters 's build [here](https://ci.ukstats.dev/job/GSS_data/job/Trade/job/csvcubed/job/ONS-International-Trade-in-Services/job/upload-to-pmd/).
Unfortunately Jenkins is currently having some problems with connecting to the docker socket so I'm going to have to leave it for now.
> Issue #320 - Attempting to fix some issues uploading legacy CSV-W code-lists to PMD

- csvcubed-pmd/csvcubedpmd/dcatcli/pmdify.py
- csvcubed-pmd/tests/behaviour/dcatcommandline.feature
> Issue #320 - Fixing dataset contents of legacy code lists.

- csvcubed/csvcubed/cli/entrypoint.py
- csvcubed/csvcubed/utils/log.py
- csvcubed/csvcubed/writers/qbwriter.py
- csvcubed/csvcubed/writers/skoscodelistwriter.py
- csvcubed/tests/behaviour/cli.feature
- csvcubed/tests/behaviour/steps/cli.py
- csvcubed/tests/unit/conftest.py
- csvcubed/tests/unit/writers/test_qbwriter.py
And some small assorted additions I made along the way.
I've fixed the behaviour of the logging functionality so it outputs log records below the `warning` level. I've also ensured that the log files rotate every 7 days, so that we keep a significant history for the user but don't end up taking up all of their storage.
> Issue #323 - Some more logging added

- csvcubed/csvcubed/cli/entrypoint.py
Added try catch and exception logging for inspect cmd
> Added try catch and exception logging for inspect command

- external-docs/docs/glossary/index.md
A basic glossary page giving definitions, sources, examples and further reading for the following terms in alphabetical order:
- aggregate
- attribute
- code-list
- CSV-W
- dimension
- literal
- measure
- observation (value)
- population characteristic
- resource
- tidy data
- unit
- URI
Please check a perhaps dubious definition of 'population characteristic' and the relevance of the further reading for URIs.
> CharlesRendle/Issue259 Basic Glossary

- csvcubed/csvcubed/utils/uri.py
- csvcubed/tests/unit/utils/test_uritests.py
> looks_like_uri should return False for windows-style paths

- external-docs/docs/guides/errors/index.md
- external-docs/docs/guides/errors/label-uri-collision.md
- external-docs/docs/guides/errors/no-observations-columns.md
- external-docs/docs/guides/errors/unknown-pydantic-error.md
- external-docs/docs/guides/qube-config.md
- external-docs/docs/quick-start/build-command.md
- external-docs/docs/quick-start/command-line.md
- external-docs/docs/quick-start/qube-config.md
- external-docs/mkdocs.yml
Completing #376 with @giraffe-technology's work; but doing the low-fi file pick to focus the scope.
> All of @Giraffe-Technology's changes, fresh main

- csvcubed/csvcubed/cli/entrypoint.py
- csvcubed/csvcubed/readers/preconfiguredtemplates.py
- csvcubed/poetry.lock
- csvcubed/pyproject.toml
- csvcubed/tests/unit/readers/test_preset_column_templates.py
These fixes come from the release candidate branches/tags which we had to make in a hurry yesterday to ensure we released working code for the demo.
> Fixing broken template lookup functionality.

- .gitignore
- external-docs/docs/guides/command-line/build-command.md
- external-docs/docs/guides/index.md
- external-docs/docs/guides/missing-observed-values.md
- external-docs/docs/guides/qube-config.md
- external-docs/docs/guides/using-templates.md
- external-docs/docs/quick-start/designing-csv.md
* No broken links
* Add guide index page
* Some formatting
* No more mermaid diagram in qube-config.md
* Wall of text increased 1000% in qube-config.md
> Documentation improvements

- csvcubed/csvcubed/cli/inspect/metadataprocessor.py
- csvcubed/csvcubed/utils/csvw.py
- csvcubed/csvcubed/utils/qb/components.py
- csvcubed/csvcubed/utils/sparql.py
- csvcubed/tests/unit/cli/inspect/test_inspectsparqlmanager.py
- csvcubed/tests/unit/cli/inspect/test_metadataprocessor.py
- csvcubed/tests/unit/readers/cubeconfig/v1_0/cassettes/test_column_template_expansion.yaml
- csvcubed/tests/unit/utils/qb/test_components.py
- csvcubed/tests/unit/utils/test_sparql.py
Most of the issues are naturally to do with how we handle paths. We need to start making an extra effort to ensure we're using pathlib in a way which minimises the impact across different platforms.
We should also find a way to add windows platform tests to our release process - perhaps we can use the VM in GCP for now as a manual process but look to move to github actions (which I believe support running stuff on windows) at a later point.
I have *not* been able to run docker tests yet. But it's important to get these fixes in ASAP regardless.
> Issue #360 - Fixing test problems on windows.

- csvcubed-devtools/poetry.lock
- csvcubed-models/csvcubedmodels/dataclassbase.py
- csvcubed-models/poetry.lock
- csvcubed-models/pyproject.toml
- csvcubed-models/tests/unit/test_dataclassbase.py
- csvcubed-pmd/poetry.lock
- csvcubed/csvcubed/__init__.py
- csvcubed/csvcubed/models/cube/catalog.py
- csvcubed/csvcubed/models/cube/qb/catalog.py
- csvcubed/csvcubed/readers/cubeconfig/v1_0/configdeserialiser.py
- csvcubed/csvcubed/schema/cube-config/v1_0/schema.json
- csvcubed/poetry.lock
- csvcubed/pyproject.toml
- csvcubed/tests/behaviour/cube.feature
- csvcubed/tests/behaviour/steps/cubes.py
- csvcubed/tests/test-cases/readers/cube-config/v1.0/cube_data_config_ok.json
- csvcubed/tests/unit/readers/cubeconfig/v1_0/test_cube_from_config_json.py
> JSON Schema fixes + Supporting parsing dates/date-times from qube-config.json 

- csvcubed/csvcubed/models/inspectdataframeresults.py
- csvcubed/tests/behaviour/inspectcli.feature
Improved logic when displaying number of observations.
> Improved logic when displaying number of observations

- .gitignore
- csvcubed/csvcubed/cli/build.py
No tests. Won't write NFR tests.
> Adds resolved path to build complete message

- external-docs/docs/guides/errors/build-command-errors/index.md
> add missing index entries for newer errors

- src/csvcubed/cli/inspect/inspectsparqlmanager.py
- src/csvcubed/definitions.py
- src/csvcubed/writers/qbwriter.py
- tests/behaviour/qbwriter.feature
- tests/behaviour/steps/cubes.py
- tests/behaviour/steps/qbwriter.py
- tests/unit/cli/inspect/test_inspectsparqlmanager.py
- tests/unit/readers/conftest.py
- tests/unit/readers/cubeconfig/v1_0/conftest.py
- tests/unit/readers/cubeconfig/v1_0/test_cube_from_config_json.py
- tests/unit/readers/cubeconfig/v1_0/test_cube_from_convention.py
- tests/unit/writers/test_qbwriter.py
> Issue #525 - Altering serialisation of `aboutUrl` values so that they can cope successfully with invalid URI chars.

- external-docs/docs/guides/errors/build-command-errors/missing-uri-template-name-error.md
- poetry.lock
- pyproject.toml
- src/csvcubed/cli/error_mapping.py
- src/csvcubed/definitions.py
- src/csvcubed/models/cube/__init__.py
- src/csvcubed/models/cube/cube.py
- src/csvcubed/models/cube/qb/__init__.py
- src/csvcubed/models/cube/validationerrors.py
- src/csvcubed/readers/cubeconfig/v1/configdeserialiser.py
- src/csvcubed/utils/qb/standardise.py
- src/csvcubed/utils/uri.py
- tests/test-cases/readers/cube-config/v1.0/error_mappings/invalid_uri_template.csv
- tests/test-cases/readers/cube-config/v1.0/error_mappings/invalid_uri_template.json
- tests/unit/readers/cubeconfig/v1_0/cassettes/test_build_config_ok.yaml
- tests/unit/readers/cubeconfig/v1_0/test_build_friendly_error_msgs.py
- tests/unit/utils/qb/validation/test_cube.py
- tests/unit/utils/test_uri.py
pr for https://app.zenhub.com/workspaces/features-squad-61b72275ac896c0010a1b00b/issues/gss-cogs/csvcubed/452
will update purl link once/if the approach gets signed off and before any merge.
I've also included a missing vcr fixture that we're generating but haven't checked into source control.
> Issue 452/invalid uri template

- external-docs/docs/guides/errors/build-command-errors/index.md
forgot the index entry for error markdown, associated pr is already approved and merged.
> add missing index entry for error

- src/csvcubed/utils/json.py
- src/csvcubed/utils/qb/components.py
- src/csvcubed/utils/sparql.py
- tests/unit/cli/inspect/test_inspectsparqlmanager.py
- tests/unit/utils/test_rdf.py
- tests/unit/utils/test_sparql.py
This PR also contains a fix for #534
> Fixing some tests on Windows

- src/csvcubed/readers/cubeconfig/v1/mapcolumntocomponent.py
- tests/unit/readers/cubeconfig/v1_0/test_cube_from_config_json.py
> Fixing date time code list serialisation.

- src/csvcubed/readers/cubeconfig/v1/columnschema.py
- tests/unit/readers/cubeconfig/v1_0/test_cube_from_config_json.py
> Mapping data_type correctly from JSON observations column definition.

- src/csvcubed/schema/cube-config/v1_3/schema.json
Satisfies #550.
The new behave tests written in [#571](https://github.com/GSS-Cogs/csvcubed/pull/571) covers the tests for this change as well.
> 550 col mappings in qube config

- poetry.lock
- pyproject.toml
- tests/unit/utils/sparqlhandler/test_sparqlmanager.py
> Upgrading csvcubed-devtools, csvcubed-models and pyparsing

- poetry.lock
- pyproject.toml
- src/csvcubed/models/cube/qb/components/attribute.py
- src/csvcubed/models/cube/qb/components/measure.py
- src/csvcubed/utils/qb/validation/observations.py
- src/csvcubed/writers/qbwriter.py
- src/csvcubed/writers/urihelpers/qbcube.py
- tests/behaviour/qbwriter.feature
- tests/behaviour/steps/qbwriter.py
- tests/unit/writers/test_qbwriter.py
> 584 alter qbwriter to support pivoted shape

- .github/workflows/main-push.yaml
- .github/workflows/pull-request.yaml
- .github/workflows/release.yaml
- .github/workflows/reusable-test.yaml
- Dockerfile
- external-docs/docs/guides/installing-python.md
- poetry.lock
- pyproject.toml
> Updated to python 3.11 #631

- .github/workflows/reusable-deploy.yaml
> #650 Attempting fix for checking is final release

- src/csvcubed/cli/error_mapping.py
- src/csvcubed/models/cube/qb/components/validationerrors.py
- src/csvcubed/writers/qbwriter.py
- tests/unit/writers/qbwriter/test_qbwriter.py
> #662 required attributes warning for pivoted shape

- src/csvcubed/utils/createlocalcopyresponse.py
- src/csvcubed/writers/qbwriter.py
I forgot to remove this line while investigating a solution to one of the original PR (#671) comments.
> 401 cleanup - Redundant line removal

- src/csvcubed/readers/cubeconfig/v1_0/templates/statistical-geography.json
Correct statistical-geography template to suppress the generation of code_list.
> added `code_list: false`

- src/csvcubed/cli/build_code_list.py
- src/csvcubed/readers/codelistconfig/codelist_schema_versions.py
- src/csvcubed/readers/cubeconfig/v1/columnschema.py
- tests/unit/readers/test_codelist_schema_deserialisation.py
Adding requested changes with #704
> Refactored cube config code list reader to use versioned deserialiser #704

- src/csvcubed/cli/inspect/inspectdatasetmanager.py
- src/csvcubed/utils/csvdataset.py
- tests/unit/cli/inspect/test_inspectdatasetmanager.py
issue 657: https://app.zenhub.com/workspaces/features-squad-61b72275ac896c0010a1b00b/issues/gh/gss-cogs/csvcubed/657
> Moving inspect functions to utils

- src/csvcubed/models/cube/qb/components/unit.py
- tests/unit/utils/test_validations.py
Finishing up responding to feedback for #674 Implement validations in the following classes PT1.
> #674 Finishing responding to feedback for validations pt1

- src/csvcubed/models/cube/catalog.py
- src/csvcubed/models/cube/columns.py
- src/csvcubed/models/cube/qb/catalog.py
- src/csvcubed/models/cube/qb/columns.py
- src/csvcubed/models/cube/qb/components/attribute.py
- src/csvcubed/models/cube/qb/components/datastructuredefinition.py
- src/csvcubed/models/cube/qb/components/dimension.py
- src/csvcubed/models/cube/qb/components/measure.py
- src/csvcubed/models/cube/qb/components/measuresdimension.py
- src/csvcubed/models/cube/qb/components/observedvalue.py
- src/csvcubed/utils/validations.py
- tests/unit/utils/test_validations.py
This ticket we added several new validations to the second half of classes that were identified as needing new ones. The PR is a follow up to the #674 "Implement validations in the following classes PT1."
Satisfies #675
> #675 Validations implementation pt2.

- src/csvcubed/writers/helpers/qbwriter/dsdtordfmodelshelper.py
- tests/unit/writers/qbwriter/test_dsdtordfmodelshelper.py
#755 Bug was noticed during the work on #703.
> #755 FIX unit component duplication BUG

- src/csvcubed/utils/qb/standardise.py
- tests/unit/utils/qb/test_standardise.py
> Support matching code-lists on code/notation as well as label.

- .github/workflows/reusable-test.yaml
- src/csvcubed/cli/inspect/inspect.py
- tests/behaviour/cli.feature
- tests/behaviour/steps/cli.py
Fixing issue introduced in previous release where code-list inspect would fail.
Satisfies issue #769.
> #769 Fixing bug when inspecting code-lists

- external-docs/docs/guides/linked-data/organisations.md
* Greater London Authority added to organisations.md
* This relates to this issue https://github.com/GSS-Cogs/ds-squad/issues/1
> Greater London Authority added

- .github/workflows/main-push.yaml
- .github/workflows/pull-request.yaml
- .github/workflows/reusable-test.yaml
Added `pandas-version: ''` to `main-push.yaml` to stop it failing on `test-in-environments` job
> Fixing main-push.yaml

- .github/workflows/release.yaml
There was an error when releasing the new version
https://github.com/GSS-Cogs/csvcubed/actions/runs/5444432557
> adding the pandas call

- src/csvcubed/models/cube/qb/validationerrors.py
- src/csvcubed/utils/log.py
- src/csvcubed/utils/qb/validation/observations.py
- src/csvcubed/writers/helpers/qbwriter/dsdtordfmodelshelper.py
- src/csvcubed/writers/helpers/qbwriter/urihelper.py
- tests/unit/cli/inspectcsvw/test_metadatainputvalidator.py
- tests/unit/readers/cubeconfig/v1_0/test_build_friendly_error_msgs.py
- tests/unit/readers/cubeconfig/v1_0/test_cube_from_convention.py
- tests/unit/writers/qbwriter/test_qbwriter.py
- tests/unit/writers/qbwriter/test_urihelper.py
- tests/unit/writers/qbwriter/testhelpers.py
> #848_Solving code smells shown in SonarCloud

- .github/workflows/main-push.yaml
- .github/workflows/pull-request.yaml
- .github/workflows/release.yaml
Version lock pandas~2.0 until #886 complete
> pandas~2.0

- src/csvcubed/writers/helpers/qbwriter/urihelper.py
- src/csvcubed/writers/qbwriter.py
- src/csvcubed/writers/skoscodelistwriter.py
Added identifying information (e.g. column title) to logger messages.
> Improved logger strings with identifying information

- poetry.lock
- pyproject.toml
setuptools version locked to <70
> setuptools version lock
